name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ['main']
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup
        uses: joeyfigaro/pnpm-config/.github/workflows/pnpm@main

      - name: Prettier fixes
        run: pnpm run prettier:write

      - uses: autofix-ci/action@551dded8c6cc8a1054039c8bc0b8b48c51dfc6ef
        with:
          commit-message: 'ci: automated fixes'
