name: Pull Request

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    name: Execute Tests
    runs-on: ubuntu-latest

    steps:
      - name: Common Workflow
        uses: joeyfigaro/pnpm-config/.github/workflows/pnpm@main

      - name: Test:CI
        run: pnpm run test:ci
