name: Pull Request

on:
  pull_request:
    branches: main
    types: [opened, synchronize]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup:
    uses: joeyfigaro/pnpm-config/.github/workflows/setup.yaml@main

  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Test:CI
        run: pnpm run test:ci
