name: Pull Request

on:
  pull_request:
    branches: main
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup:
    uses: joeyfigaro/workflows/.github/workflows/pnpm/setup.yaml@main
    with:
      pnpm_version: 10.7.0
      node_version: 22.11.0
    secrets:
      GITHUB_CI_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: setup
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Test:CI
        run: pnpm run test:ci

